name: ci-app-test
on: push
jobs:
  build:
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master	
      - run: make setup
      - run: make test
      - name: run linter
        run: make lint
